name: insidepulse_app
description: "Personalized audio news briefings delivered on your schedule"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
